// Do not repeat keys...
export default {
  1: "Talk to me about",
  2: "My worst fear is",
  3: "If I could change one thing in the world it would be...",
  4: "My favourite memory is",
  5: "If there's anything I could be I would be",
  6: "My favourite thing in the world is",
  7: "A real eye opening experience I had",
  8: "I am here for",
  9: "My biggest pet peeve is",
  10: "What I look for in a partner is",
  11: "My political views are",
  12: "A superstition I believe in ",
  13: "My ex would describe me as",
  14: "My favourite fantasy",
  15: "My idea of an ideal date is",
  16: "My favourite drink is",
  17: "My favourite book/author is",
  18: "My favourite show/movie",
  19: "My favourite song/album/band",
  20: "My quarantine experience",
  21: "My view on climate change",
};
