export default {
  1: "Talk to me about",
  2: "My worst fear is",
  3: "if I could change one thing in the world it would be...",
  4: "My favourite memory is",
  5: "if there's anything I could be I would be",
  6: "my most favourite thing in the world is",
  7: "a real eye opening experience I had",
  8: "what am I here for",
  9: "My biggest pet peeve is",
  10: "what I look for in a partner is",
  11: "my political views are",
  12: "a superstition I believe in ",
  13: "my ex would describe me as",
  14: "my favourite fantasy",
  15: "My idea of an ideal date is",
  16: "My favourite drink is",
  17: "my favourite book/author is",
  18: "my favourite show/movie",
  19: "my favourite song/album/band",
  20: "my quarantine experience",
  21: "my view on climate change",
};
